### PR TITLE
Devise styling

### PR DESCRIPTION
**Pull request by ethansiegl**
Did some styling on the devise pages to make them look nice

### CODE REVIEW

**Comment by zoheb391** [comment]
I like the font :+1

**Comment by LauraUmana** [comment]
Awesome! I'll merge these changes tomorrow night :)

**Comment by ethansiegl** [comment]
@LauraUmana I had some free time so I fixed the merge issues. I think it should be good to go

**Comment by ilyakrasnov** [comment]
Awesome job!

**Pull request merged**
