### PR TITLE
Games show

### PR DESCRIPTION
**Pull request by AncyentMariner**
Here's what I have for the game board. Everyone take a look at it please, and let me know what you think. 
We may have to change the table id references. Maybe the a1-h8 (instead of the 0,0 - 7,7) system makes more sense. What do you all think?

### CODE REVIEW

**Comment by ethansiegl** [comment]
Looks great! I think using the a1-h8 system might be helpful

**Comment by zoheb391** [comment]
Looks good, anyone care to explain the benefits of using the a1-h8 system? 
Also, maybe the css can go into a separate master.css to keep things organized? But that can be done on a later commit

**Comment by LauraUmana** [comment]
Looks good so far. It may be helpful to change it to a1- h8 so we don't get confused?
And I think there is one little thing you may need to change. You will have to push the h1 that is in the head to the body portion.

**Comment by AncyentMariner** [comment]
The a1-h8 reference system is just a different (more common, for chessboards, too) way to representing the board. It gives the rows and columns different reference points (rows are 1-8 and columns are a-h) so each square has unique coordinates, but the columns and rows aren't easily confused. 
I'll change it to a1-h8 for now, and we can make changes later if there's any issue. 
Thanks, Laura. I'll move the H1 tag. It's just a filler heading for now. I imagine we'll change it to something else later.

**Comment by AncyentMariner** [comment]
Zoheb and I discussed this and we think it all looks good, so he gave me the go-ahead to merge.

**Pull request merged**
